project/bounties/urls.py
from django.urls import path
from .views import (DeleteBounty, RecentBounties, ViewBounty, CreateBounty,
                    CreateSolution, DeleteSolution, award_solution)

app_name = 'bounties'

urlpatterns = [
    path('', RecentBounties.as_view(), name="recent_bounties"),
    path('<int:pk>', ViewBounty.as_view(), name="view_bounty"),
    path('create', CreateBounty.as_view(), name="create_bounty"),
    path('delete/<int:pk>', DeleteBounty.as_view(), name="delete_bounty"),
    path('<int:pk>/solution/create',
         CreateSolution.as_view(), name="create_solution"),
    path('<int:bounty_pk>/solution/delete/<int:pk>',
         DeleteSolution.as_view(), name="delete_solution"),
    path('<int:bounty_pk>/solution/award/<int:pk>',
         award_solution, name='award_solution'),
]

project/bounties_api/urls.py
from django.urls import path
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import BountyViewSet, SolutionViewSet

app_name = 'bounties_api'

router = DefaultRouter()
router.register(r'bounties', BountyViewSet, basename='bounties')
router.register(r'solution', SolutionViewSet, basename='solutions')

urlpatterns = [
    path('', include(router.urls)),
]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bounty/', include('bounties.urls'), name='bounties'),
    path('api/user/', include('users_api.urls'), name='user_api'),
    path('api/', include('bounties_api.urls'), name='bounties_api'),
]

project/users_api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from .views import UserDetail, UserList

app_name = 'users_api'

urlpatterns = [
    path('', UserList.as_view(), name='user_list'),
    path('<int:pk>', UserDetail.as_view(), name='user_detail'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

project/bounties/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class Bounty(models.Model):
    ONGOING = 0
    FINISHED_AWARDED = 1
    FINISHED_EXPIRED = 2
    DELETED = 3
    STATUS_CHOICES = [(ONGOING, 'Ongoing'), (FINISHED_AWARDED, 'Awarded'),
                      (FINISHED_EXPIRED, 'Expired'), (DELETED, 'Deleted')]

    title = models.CharField(max_length=40)
    description = models.TextField(max_length=1000)
    reward = models.PositiveSmallIntegerField()
    creation_date = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(
        User, models.DO_NOTHING, primary_key=False, null=True, related_name='bounties')
    status = models.PositiveSmallIntegerField(
        choices=STATUS_CHOICES, default=ONGOING)
    awarded_solution = models.OneToOneField(
        'Solution', models.SET_NULL, null=True, primary_key=False, related_name='+')

    class Meta:
        constraints = [
            models.CheckConstraint(check=models.Q(
                reward__range=(1, 500)), name='reward_range'),
        ]

    def get_absolute_url(self):
        return reverse('bounties:view_bounty', kwargs={'pk': self.id})

    def __str__(self):
        return self.title


class Solution(models.Model):
    AWARDED = 0
    UNAWARDED = 1
    DELETED = 2
    STATUS_CHOICES = [(AWARDED, 'Awarded'), (UNAWARDED,
                                             'Unawarded'), (DELETED, 'Deleted')]

    creator = models.ForeignKey(
        User, models.DO_NOTHING, primary_key=False, related_name='solutions')
    bounty = models.ForeignKey(
        Bounty, models.CASCADE, primary_key=False, related_name='solutions')
    status = models.PositiveSmallIntegerField(
        choices=STATUS_CHOICES, default=UNAWARDED)
    text = models.CharField(max_length=1000)

    def __str__(self):
        return f"Solution {self.id} to {self.bounty}"

project/users_api/models.py
from django.db import models

# Create your models here.

project/bounties/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied, BadRequest
from bounties.models import Bounty, Solution


class RecentBounties(ListView):
    template_name = 'bounties/index.html'
    context_object_name = 'bounties_list'

    def get_queryset(self):
        return Bounty.objects.exclude(status=Bounty.DELETED)


class ViewBounty(DetailView):
    model = Bounty
    template_name = 'bounties/view_bounty.html'


class DeleteBounty(UserPassesTestMixin, DeleteView):
    model = Bounty
    success_url = reverse_lazy('bounties:recent_bounties')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.status = Bounty.DELETED
        self.object.save()
        return HttpResponseRedirect(success_url)

    def test_func(self):
        bounty = self.model.objects.get(id=self.kwargs['pk'])
        return self.request.user == bounty.creator


class CreateBounty(LoginRequiredMixin, CreateView):
    model = Bounty
    fields = ['title', 'description', 'reward']
    template_name = 'bounties/create_bounty.html'

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class CreateSolution(LoginRequiredMixin, CreateView):
    model = Solution
    fields = ['text']

    def form_valid(self, form):
        bounty = Bounty.objects.get(id=self.kwargs['pk'])
        form.instance.bounty = bounty
        form.instance.creator = self.request.user
        self.success_url = reverse_lazy(
            'bounties:view_bounty', args=(self.kwargs['pk'],))
        return super().form_valid(form)


class DeleteSolution(UserPassesTestMixin, DeleteView):
    model = Solution
    success_url = reverse_lazy('bounties:recent_bounties')

    def form_valid(self, form):
        success_url = reverse_lazy(
            'bounties:view_bounty', args=(self.kwargs['bounty_pk'],))
        self.object.status = Solution.DELETED
        self.object.save()
        return HttpResponseRedirect(success_url)

    def test_func(self):
        solution = self.model.objects.get(id=self.kwargs['pk'])
        return self.request.user == solution.creator


def award_solution(request, bounty_pk, pk):
    bounty = get_object_or_404(Bounty, pk=bounty_pk)
    solution = get_object_or_404(Solution, pk=pk)

    if not request.user.is_authenticated or request.user != bounty.creator:
        raise PermissionDenied
    if request.method != 'GET':
        raise BadRequest

    bounty.awarded_solution = solution
    bounty.status = Bounty.FINISHED_AWARDED
    solution.status = Solution.AWARDED
    bounty.save()
    solution.save()

    return redirect(bounty, reverse('bounties:view_bounty', args=(bounty_pk,)))

project/bounties_api/views.py
from rest_framework import permissions, status
from rest_framework.response import Response
from rest_framework import viewsets


from bounties.models import Bounty, Solution
from .serializers import BountySerializer, SolutionSerializer
from .permissions import IsOwnerOrReadOnly

class BountyViewSet(viewsets.ModelViewSet):
    queryset = Bounty.objects.all()
    serializer_class = BountySerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,
                        IsOwnerOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(creator=self.request.user)

    def perform_destroy(self, instance):
        instance.status = Bounty.DELETED
        instance.save()
        return Response(status=status.HTTP_204_NO_CONTENT)


class SolutionViewSet(viewsets.ModelViewSet):
    queryset = Solution.objects.all()
    serializer_class = SolutionSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,
                        IsOwnerOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(creator=self.request.user)

    def perform_destroy(self, instance):
        instance.status = Solution.DELETED
        instance.save()
        return Response(status=status.HTTP_204_NO_CONTENT)

project/users_api/views.py
from rest_framework import generics
from django.contrib.auth.models import User

from .serializers import UserSerializer


class UserList(generics.ListAPIView):
    """
    List all users
    """

    queryset = User.objects.all()
    serializer_class = UserSerializer

class UserDetail(generics.RetrieveAPIView):
    """
    Retrieve a User instance
    """

    queryset = User.objects.all()
    serializer_class = UserSerializer

project/bounties/templates/bounties/bounty_confirm_delete.html
{% extends 'project/header.html' %}

{% block page_content %}

<br>
<div class="container">
<div class="bg-light p-5 rounded border border-danger">
<h2>Are you sure you want to delete this bounty?</h2>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input class="btn btn-danger" type="submit" value="I'm sure">
</form>
</div>
</div>

{% endblock page_content %}

project/bounties/templates/bounties/create_bounty.html
{% extends 'project/header.html' %}
{% block page_content %}
<br>
<div class="container-fluid">
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</div>
{% endblock page_content %}

project/bounties/templates/bounties/index.html
{% extends 'project/header.html' %}

{% block page_content %}
<br>
{% for bounty in bounties_list %}
    <div class="container-sm border rounded p-1 border-dark">
        <div class="row">
            <div class="col-1"><h4>${{bounty.reward}}</h4></div>
            <div class="col"><h4><a href="{% url 'bounties:view_bounty' bounty.id %}">{{bounty}}</a></h4></div>
        </div>
    </div>
    <br>
{% endfor %}
{% endblock page_content %}

project/bounties/templates/bounties/solution_confirm_delete.html
{% extends 'project/header.html' %}

{% block page_content %}

<br>
<div class="container">
<div class="bg-light p-5 rounded border border-danger">
<h2>Are you sure you want to delete this solution?</h2>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input class="btn btn-danger" type="submit" value="I'm sure">
</form>
</div>
</div>

{% endblock page_content %}

project/bounties/templates/bounties/solution_form.html
{% extends 'project/header.html' %}

{% block page_content %}

<br>
<div class="container">
<div class="bg-light p-5 rounded border border-danger">
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input class="btn btn-success" type="submit">
</form>
</div>
</div>

{% endblock page_content %}

project/bounties/templates/bounties/view_bounty.html
{% extends 'project/header.html' %}
{% block page_content %}
<br>
<div class="container">
   <div class="bg-light p-5 rounded border border-dark">
    {% if bounty.status != 0 %}
    {{ bounty.status }}
    {% endif %}
    <h1>{{ bounty.title }}</h1>
    <p>Creator: {{ bounty.creator }}. Reward: ${{ bounty.reward }}</p>
    <p class="lead">{{ bounty.description }}</p>
    <a href="{% url 'bounties:create_solution' bounty.id %}"><button class="btn btn-primary">Create solution</button></a>
    {% if user == bounty.creator %}
    <a href="{% url 'bounties:delete_bounty' bounty.id %}"><button class="btn btn-danger">Delete</button></a>
    {% endif %}
  </div> 
</div>
<br>
<div class="container">
  {% if bounty.awarded_solution %}
    <div class="bg-light p-2 rounded border border-info">
      <p class="lead">{{ bounty.awarded_solution.text }}</p>
      {{ bounty.awarded_solution.creator.username }}
      {% if user == bounty.awarded_solution.creator %}
      <a href="{% url 'bounties:delete_solution' bounty.id bounty.awarded_solution.id %}"><button class="btn btn-danger">Delete</button></a>
      {% endif %}
    </div>
    <br>
  {% endif %}
{% for solution in bounty.solutions.all %}
  {% if solution.status != solution.DELETED and solution != bounty.awarded_solution %}
    <div class="bg-light p-2 rounded border border-dark">
    <p class="lead">{{ solution.text }}</p>
    {{ solution.creator.username }}
    {% if user == bounty.creator %}
      <a href="{% url 'bounties:award_solution' bounty.id solution.id %}"><button class="btn btn-success">Award</button></a>
    {% endif %}
    {% if user == solution.creator %}
      <a href="{% url 'bounties:delete_solution' bounty.id solution.id %}"><button class="btn btn-danger">Delete</button></a>
    {% endif %}
  </div>
  <br>
  {% endif %}
{% endfor %}
</div>


{% endblock page_content %}

project/templates/project/header.html
{% load static %}
<link rel="stylesheet" href="{% static 'bootstrap-5.2.0/css/bootstrap.css' %}">

<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="{% url 'bounties:recent_bounties' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <circle cx="18" cy="16" r="13" stroke="white" stroke-width="2" fill="#343a40" />
                </svg>
                <h1>Bounties</h1>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"></ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search"></form>

            <div class="text-end">
                {% if request.user.is_authenticated %}
                <a href="{% url 'bounties:create_bounty' %}"><button type="button" class="btn btn-primary me-2">New bounty</button></a>
                <a href="{% url 'logout' %}"><button type="button" class="btn btn-link me-2">Sign out</button></a>
                {% else %}
                <a href="{% url 'login' %}"><button type="button" class="btn btn-outline-light me-2">Login</button></a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

{% block page_content %}
{% endblock page_content %}